service: serverless-lambda
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  stage: dev
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - ses:*
      Resource: "*"

plugins:
  # - serverless-auto-swagger
  - serverless-webpack
  - serverless-add-api-key
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 5000
  tableName: playerpoints
  apiKeys:
    - name: free
      usagePlan:
        name: freeUsagePlan
        quota:
          limit: 3
          period: DAY
        throttle:
          rateLimit: 5
          burstLimit: 10

    - name: paid
      usagePlan:
        name: paidUsagePlan
        quota:
          limit: 15
          period: MONTH
        throttle:
          rateLimit: 20
          burstLimit: 25

functions: ${file(yml/functions.yml)}

resources:
  - ${file(yml/dynamo.yml)}
